"""empty message

Revision ID: 2e5a4f437d4d
Revises: 
Create Date: 2023-02-26 15:27:08.648348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e5a4f437d4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blocklist_jti'), ['jti'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sizes', sa.Enum('SMALL', 'MEDIUM', 'LARGE', 'EXTRA_LARGE', name='sizes'), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('order_status', sa.Enum('PENDING', 'IN_TRANSIT', 'DELIVERED', name='orderstatus'), nullable=True),
    sa.Column('flavour', sa.Enum('BBQ_CHICKEN', 'PEPPERONI', 'SAUSAGE', 'CHEESE', 'EXTRA_CHEESE', 'BACON', 'PINEAPPLE', 'MARGHERITA', name='orderflavour'), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('customer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('users')
    with op.batch_alter_table('blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blocklist_jti'))

    op.drop_table('blocklist')
    # ### end Alembic commands ###
